apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-cluster
  region: us-east-1
  version: "1.30"
vpc:
  id: vpc-041f93f892937f052
  securityGroup: "sg-03a482c52bb44ff09"
  subnets:
    private:
      us-east-1a: { id: subnet-0de4cee886cf3a4a3 }
      us-east-1b: { id: subnet-0f60febe92773cd98 }
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
iam:
  serviceRoleARN: "arn:aws:iam::157516227132:role/EksClusterRole"
  withOIDC: true
managedNodeGroups:
  - name: eks-nodes
    minSize: 2
    maxSize: 2
    desiredCapacity: 2
    volumeSize: 20
    privateNetworking: true
    instanceType: t3.medium
    iam:
      instanceRoleARN: arn:aws:iam::157516227132:role/EksNodeRole
